version: "3.8"
services:
  flask-backend:
    build: ./backend
    ports:
      - 5000:8000
    volumes:
      - ./frontend/src/assets/generated_images:/app/image_data
    depends_on:
      - redis
  vue-frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/app
      - /app/node_modules
  redis:
    image: redis
    ports:
      - 6379:6379
