version: "3.8"
services:
  flask-backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - image-data:/app/image_data
  vue-frontend:
    build: ./frontend
    ports:
      - 3000:3000
    volumes:
      - image-data:/app/public/generated_images
      - ./frontend:/app
      - /app/node_modules
volumes:
  image-data:
